on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java 17 설정
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-17
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle Wrapper 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Gradle 빌드
        run: ./gradlew clean build

      - name: Checkout standard-images repo
        uses: actions/checkout@v4
        with:
          repository: yoon-youngjin/standard-images
          path: standard-images

      - name: Checkout standard-images repository
        uses: actions/checkout@v4
        with:
          repository: yoon-youngjin/standard-images
          path: standard-images

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        run: |
          docker build \
            -f standard-images/docker/Dockerfile \
            .

      - name: Check image
        run: docker images 
