on:
  workflow_dispatch:
    inputs: # 이걸 어떻게 입력받지않고 가져올 수 있을까?
      ecr_repository:
        description: 'ECR 레포지토리명'
        required: true
        type: string
        default: 'dummy'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java 17 설정
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-17
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle Wrapper 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Gradle 빌드
        run: ./gradlew clean build

      - name: Checkout standard-images repo
        uses: actions/checkout@v4
        with:
          repository: yoon-youngjin/standard-images
          path: standard-images

      - name: Checkout standard-images repository
        uses: actions/checkout@v4
        with:
          repository: yoon-youngjin/standard-images
          path: standard-images

      - name: AWS 자격 증명 구성
        uses: aws-actions/configure-aws-credential@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: ECR 로그인
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker 이미지 빌드, 태그 및 ECR 푸시
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f standard-images/docker/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG 
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
