name: CI/CD Pipeline
on:
  push:
    branches: [ develop ]

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  build:
    needs: [ test ]
    uses: ./.github/workflows/build.yaml
    with:
      profile: ${{ github.ref == 'refs/heads/develop' && 'dev' || 'live' }}

  # CD 단계 추가