name: Validation

on:
  workflow_dispatch:
  pull_request:
    branches: [ develop ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: scripts 실행 권한 부여
        run: chmod +x ./.github/workflows/scripts/*.sh

      - name: Validate branch naming convention
        run: |
          BRANCH="${{ github.head_ref }}"
          ./.github/workflows/scripts/validate-branch-convention.sh "$BRANCH"
      
    
    
